let stream; const $=s=>document.querySelector(s); const step=n=>{document.querySelectorAll('.step').forEach(x=>x.classList.remove('active')); $(`#step${n}`).classList.add('active');};
$('#grantPermissions').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}}); $('#video').srcObject=stream; step(1);}catch{showError('Camera access denied.');}};
$('#captureBtn').onclick=()=>{const v=$('#video'),c=$('#canvas'),img=$('#photoPreview'); c.width=v.videoWidth; c.height=v.videoHeight; c.getContext('2d').drawImage(v,0,0); c.toBlob(b=>{const u=URL.createObjectURL(b); img.src=u; img.onload=()=>URL.revokeObjectURL(u); v.classList.add('hidden'); img.classList.remove('hidden'); stream.getTracks().forEach(t=>t.stop()); $('#processBtn').classList.remove('hidden'); step(2);},'image/jpeg');};
$('#uploadBtn').onclick=()=>$('#fileInput').click();
$('#fileInput').onchange=e=>{const f=e.target.files[0]; if(!f)return; const u=URL.createObjectURL(f); $('#photoPreview').src=u; $('#video').classList.add('hidden'); $('#photoPreview').classList.remove('hidden'); $('#processBtn').classList.remove('hidden'); step(2);};
$('#processBtn').onclick=async()=>{const img=$('#photoPreview').src; step(2); $('.spinner').style.display='block'; $('#error').classList.add('hidden'); try{const res=await fetch('/api/process-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:img})}); const data=await res.json(); if(!res.ok) throw new Error(data.message||'Server error'); displayResult(img,data.solution); step(3);}catch(err){showError(err.message);} $('.spinner').style.display='none';};
function displayResult(imgSrc,md){ $('#capturedImg').src=imgSrc; const html=marked.parse(md.replace(/\$(.*?)\$/g,(m,math)=>`<span class="math-block">${math}</span>`)); $('#solution').innerHTML=html; $('#solution').querySelectorAll('.math-block').forEach(el=>katex.render(el.textContent,el,{throwOnError:false,displayMode:true}));}
function showError(msg){$('#error').textContent=msg; $('#error').classList.remove('hidden');}
$('#startOver').onclick=()=>location.reload();
